image: docker:latest
services:
  - docker:dind
stages:
  - build
  - test
  - deploy

variables:
  IMG_CURRENT: "registry.gitlab.com/mohammadvarmazyar/helloworld/api:$CI_JOB_ID"
  IMG_LATEST: "registry.gitlab.com/mohammadvarmazyar/helloworld/api:latest"


build:
  stage: build
  script:
    - docker build -t $IMG_CURRENT src/
    ##### $DOCKER_LOGIN_KEY can be obtained in GitLab as a Personal Access Token #####    
    - docker login -u mohammadvarmazyar -p $DOCKER_LOGIN_KEY registry.gitlab.com
    - docker images
    - docker push $IMG_CURRENT

##### Unit tests and Integration tests #####
test:
  stage: test 
  image: python:3-alpine
  script:
    - docker run --name $CI_JOB_ID-postgres --network $NETWORK_TEST -e POSTGRES_PASSWORD=$POSTGRES_PASS_TEST -d postgres
    - >
       docker run -d 
       --name "$CI_PROJECT_NAME-$CI_PIPELINE_ID" 
       -e "DB_NAME=$DB_NAME_TEST" 
       -e "DB_PORT=$DB_PORT_TEST" 
       -e "DB_HOST=$CI_JOB_ID-postgres"
       -e "DB_USER=$CI_USER_TEST"
       -e "DB_PASS=$DB_PASS_TEST"
       --network $NETWORK_TEST
       $IMG_CURRENT

    - docker exec -i -u root $CI_PROJECT_NAME-$CI_PIPELINE_ID bash -c 'python3 -m unittest discover -s tests/ -p '*_test.py' -v'
    - docker rm -f $CI_PROJECT_NAME-$CI_PIPELINE_ID
    - docker rm -f $CI_JOB_ID-postgres
  only:
    - master

deploy:
  stage: deploy
  image: python:3-alpine
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    containerName: "api"
    taskDefinitionFile: "/tmp/taskDefinitionFile"
    taskDefinitionName: "update-api"
    serviceName: "api"
  before_script:
    ##### Install the AWS CLI #####
    - pip3 install awscli --upgrade --user
    - aws --version
  script:
    - echo 'update task definition...'
    - aws ecs register-task-definition --cli-input-json file://$taskDefinitionFile --region $AWS_DEFAULT_REGION > /dev/null
    - echo 'update our service with that last task..'
    - aws ecs update-service --service $serviceName --task-definition $taskDefinitionName --region $AWS_DEFAULT_REGION  > /dev/null    
  environment:
    name: ci
    ##### This is the URL seen under 'DNS name' when the LB was created #####
    url: $PROD_LOAD_BALANCER_URL
  only:
    - master