---
- hosts: databases
  vars:
  aws_rds                 :
    - security_group_id   : "sg-3a27b45z"
      publicly_accessible : False
      db_engine           : "postgres"
      db_name             : "api_db"
      instance_name       : "ap_db"
      engine_version      : "9.4.5"
      size                : "30"
      instance_type       : "db.t2.micro"
      wait                : true
      wait_timeout        : 600
      command             : "create"
      username            : "api_user"
      password            : "api_pass_secure"

  roles:
     - { role: ansible-aws-rds }